
// console.log("hello world kerwin")
import React from 'react'
import ReactDOM from 'react-dom'
// import {Provider} from 'react-redux'
// import {store} from './06-react-redux/redux/store.js'
// import App from './14-react-补充/memo/App'
// import App from './01-base/10-todolist.js'
// import App from './01-base/11-dangerouslySetInnerHTML.js'
// import App from './01-base/12-卖座选项卡.js'
// import App from './01-base/13-setState同步异步.js'
// import App from './01-base/14-betterScroll.js'
// import App from './01-base/15-betterscroll-cinema.js'
// import App from './01-base/16-props.js'
// import App from './01-base/17-props函数式组件.js'
// import App from './01-base/18-状态vs属性.js'
// import App from './01-base/19-非受控.js'
// import App from './01-base/20-受控.js'
// import App from './01-base/21-受控cinema.js'
// import App from './02-advanced/01-子传父.js'
// import App from './02-advanced/02-非受控卖座选项卡功能.js'
// import App from './02-advanced/03-受控卖座选项卡.js'
// import App from './02-advanced/04-父子通信版-表单域组件.js'
// import App from './02-advanced/05-ref版-表单域组件.js'
// import App from './02-advanced/06-中间人模式.js'
// import App from './02-advanced/07-发布订阅.js'
// import App from './02-advanced/08-订阅发布模式案例.js'
// import App from './02-advanced/09-context.js'
// import App from './02-advanced/10-插槽.js'
// import App from './02-advanced/11-插槽抽屉.js'
// import App from './02-advanced/12-生命周期-初始化.js'
// import App from './02-advanced/13-生命周期-初始化案例.js'
// import App from './02-advanced/14-生命周期-更新阶段1.js'
// import App from './02-advanced/15-生命周期-更新阶段2.js'
// import App from './02-advanced/16-生命周期-更新阶段2-案例.js'
// import App from './02-advanced/17-生命周期-更新阶段3.js'
// import App from './02-advanced/18-生命周期-更新阶段3-案例.js'
// import App from './02-advanced/19-生命周期-销毁.js'
// import App from './03-hooks/01-useState.js'
// import App from './03-hooks/02-todolist.js'
// import App from './03-hooks/03-useEffect.js'
// import App from './03-hooks/04-useEffect2.js'
// import App from './03-hooks/05-useEffect2-案例.js'
// import App from './03-hooks/06-useEffect3.js'
// import App from './03-hooks/07-useCallback1.js'
// import App from './03-hooks/09-useMemo.js'
// import App from './03-hooks/10-useRef.js'
// import App from './03-hooks/11-useRef-保存值.js'
// import App from './03-hooks/12-useContext.js'
// import App from './03-hooks/13-useReducer1.js'
// import App from './03-hooks/14-useRedeucer2.js'
// import App from './03-hooks/15-useReducer3.js'
// import App from './03-hooks/16-自定义hooks.js'
// import App from './04-router/App.js'
// import App from './05-redux/App.js'
// import App from './06-react-redux/App.js'
// import App from './09-immutable/01-base.js'
// import App from './09-immutable/02-map.js'
// import App from './14-react-补充/portal/App.js'
// import App from './14-react-补充/懒加载/App.js'
// import App from './11-styled-components/App.js'
// import App from './11-styled-components/01-透传props.js'
// import App from './11-styled-components/02-样式化组件.js'
import App from './11-styled-components/03-样式扩展.js'
// import {Provider}  from 'mobx-react'
// import store from './10-mobx/04-router/mobx/store'
ReactDOM.render(
    // <React.StrictMode>
     //<Provider store={store}>
        <App/>
     //</Provider>
    
    // </React.StrictMode>
    ,document.getElementById("root"))

